
package app.biblioteca.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "BibliotecaWSImplService", targetNamespace = "http://service.biblioteca.app/", wsdlLocation = "https://localhost/biblioteca/bibliotecaservice?wsdl")
public class BibliotecaWSImplService
    extends Service
{

   private final static URL BIBLIOTECAWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(app.biblioteca.service.BibliotecaWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = app.biblioteca.service.BibliotecaWSImplService.class.getResource(".");
            url = new URL(baseUrl, "https://localhost/biblioteca/bibliotecaservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://localhost/biblioteca/bibliotecaservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BIBLIOTECAWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public BibliotecaWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

     public BibliotecaWSImplService() {
        super(BIBLIOTECAWSIMPLSERVICE_WSDL_LOCATION, new QName("http://service.biblioteca.app/", "BibliotecaWSImplService"));
    }

    /**
     *
     * @return
     *     returns BibliotecaWS
     */
    @WebEndpoint(name = "BibliotecaWSImplPort")
    public BibliotecaWS getBibliotecaWSImplPort() {
        return super.getPort(new QName("http://service.biblioteca.app/", "BibliotecaWSImplPort"), BibliotecaWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliotecaWS
     */
    @WebEndpoint(name = "BibliotecaWSImplPort")
    public BibliotecaWS getBibliotecaWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.biblioteca.app/", "BibliotecaWSImplPort"), BibliotecaWS.class, features);
    }

}
